apiVersion: pipe.seg.dev/v1
pipeline_steps:
  - name: validate
    trigger_events:
      - pull_request
      - merge_request
    branches:
      - qa
      - main
    image: python:3.11.7-bookworm
    environment:
      PRD_TESTE: "PRD"
      LOCAL_TESTE: "REPO"
    commands:
      - python3 pip install -r ./requirements/requirements_install.txt
      - make print-teste
      - echo $PRD_TESTE

  - name: build
    trigger_events:
      - merge_request
    branches:
      - qa
      - main
    image: python:3.11.7-bookworm
    commands:
      - echo "Rodando build"
      - make print-teste

  - name: deploy
    trigger_events:
      - merge_request
    branches:
      - qa
      - main
    image: python:3.11.7-bookworm
    runAfter:
      - build
    commands:
      - echo "Deploy para prod"
      - make print-teste

  - name: teste
    trigger_events:
      - pull_request
    branches:
      - qa
      - main
    image: python:3.11.7-bookworm
    environment:
      PRD_TESTE: "PRD"
      LOCAL_TESTE: "REPO"
    runAfter:
      - validate
    commands:
      - echo LOCAL_TESTE
      - echo PRD_TESTE
      - make print-teste
